---
title: "Article 2: Your phone could reveal your radiation exposure after a nuclear disaster "
description: |
  Testing personal electronics could help people who need lifesaving treatment get it faster
author:
  - name: Alexi Ronneau
    url: {}
date: 11-03-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article : https://www.sciencenews.org/article/phones-reveal-radiation-exposure-after-nuclear-disaster By Maria Temming (January 14, 2019)

Word count: 352 words

## VOCABULARY:

| Word from the text | synonym/definition in English             | French translation                    |
| ------------------ | ----------------------------------------- | ------------------------------------- |
| insight            | uncountable (profound perception)         | perspicacité, vision                  |
| gauge              | (measure) (estimate)                      | jauger, mesurer                       |
| whereas            | (while in contrast)                       | tandis que, alors que                 |
| flood              | (water)                                   | inonder                               |
| defect             | (imperfection)                            | défaut                                |
| glow               | (light)                                   | lueur                                 |
| wavelength         | (physics: distance between waves)         | longueur d'ondes                      |
| reshuffling        | (reorganization of roles)                 | remaniement, réorganisation           |
| whether            | (if)                                      | si                                    |
| induced            | as suffix (caused by the thing specified) | provoqué par [qch], causé par [qch]   |
| facility           | (building, unit)                          | établissement, installation, complexe |

## ANALYSIS TABLE ABOUT THE STUDY:

**Researchers?**

The autor of the article: Maria Temming

Maria Temming is the staff reporter for physical sciences, covering everything from chemistry to computer science and cosmology. She has bachelor's degrees in physics and English, and a master's in science writing.

the coauthor Robert Heyes :  a nuclear engineer at North Carolina State University in Raleigh

**Published in? when (if mentioned)?**

Published in sciencenews on January 14, 2019

**General topic**

In the Chemistery Topic 

**Procedure/what was examined**

The scientists tested their technique by blasting surface mount resistors
with differents quantity of grays (units of the radiation)

**Conclusions/discovery**

A phone can reveal the radiation exposure after a uclear disaster and it can help to save people 

**Remaining questions**

/
