---
title: "Artcile 5 : Researchers perfect nanoscience tool for studies of nuclear waste storage"
description: |
  Studying radiation chemistry and electronic structure of materials at scales smaller than nanometers, scientists prepared samples of clay in ultra-thin layers. Working at the TRIUMF particle accelerator, they bombarded the samples with antimatter subatomic particles. They found their system is a proven tool for radiation studies of material to be used to store nuclear waste -- important for Canadian nuclear industry looking to build its first geological repository.
author:
  - name: Alexi Ronneau
    url: {}
date: 12-15-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: https://www.sciencedaily.com/releases/2019/12/191212141919.htm University of Guelph, December 12, 2019

Word count: 481 words

## VOCABULARY:

| Word from the text | Synonym/definition in English         | French translation              |
| ------------------ | ------------------------------------- | ------------------------------- |
| reuse              | (use again)                           | réutiliser                      |
| spinoff            | ([sth] that develops from [sth] else) | produit dérivé                  |
| ultimately         | (basically)                           | en fin de compte, en définitive |
| vault              | (architecture: arch)                  | voûte                           |
| bundle             | (bunch, group)                        | paquet                          |
| repository         | (storage place)                       | entrepôt                        |
| entomb             | formal (bury: a dead body)            | inhumer                         |
| provide [sth]      | (furnish, supply)                     | (apporter)fournir               |
| sample             | (representative piece)                | échantillon                     |
| intriguing         | (interesting)                         | fascinant                       |
| compound           | (combination)                         | mélange                         |

## ANALYSIS TABLE ABOUT THE STUDY:

**Researchers?**

University of Guelph

**Published in? when (if mentioned)?**

Published in Sciencedaily on December 12, 2019

**General topic**

Nuclear energy

**Procedure/what was examined**

It takes almost 100,000 years for radioactivity from nuclear waste to return to the level of natural uranium in the ground.
Experts aim to use deep geological repositories to permanently entomb the material. Buried in rock formations hundreds of metres underground, the fuel containers would be held in engineered and natural barriers such as clays to shield people and the environment from radiation.

**Conclusions/discovery**

The research team's findings provide a new way to study sub-nano materials and chemical processes in confined environments.

**Remaining questions**

/
