---
title: "Article 1: Safer Nuclear Reactors Are on the Way"
description: |
  Resilient fuels and innovative reactors could enable a resurgence of nuclear power
author:
  - name: Alexi Ronneau
    url: {}
date: 10-20-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: https://www.scientificamerican.com/article/safer-nuclear-reactors-are-on-the-way/    By Mark Fischetti (July 1, 2019)

Word count: 568 words

## VOCABULARY: 

| Word from the text | Synonym/definition in English                                                                | French translation                             |
| ------------------ | -------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| Resilient          | Elastic, springy, flexible,... / having resilience                                           | Elastique / resistant                          |
| Pellets of uranium | Pill, bullet,... / a small ball                                                              | Boulettes d'uranium                            |
| Readily            | Willingly, gladly, happily,...                                                               | Facilement / aisément / volontier / rapidement |
| Self-sustaining    | /                                                                                            | Autonome / indépendant                         |
| Meltdown           | The melting of the core of a nuclear reactor , due to inadequate cooling of the fuel element | Fusion                                         |
| Hastening          | Rush, move quickly,... / to move or act with haste                                           | Precipiter / accelerer                         |
| Slip               | Slide, skid,... / to became involved or absorbed easily                                      | Glisser                                        |
| Phase              | Stage, period, step, part,... / a stage in process of change or development                  | Etape                                          |
| Squelch            | Crush, censure, suppress,... / to supress or silence, as with force or a crushing response   | Ecraser                                        |
| Overheating        | Heat to much,... / to become too hot or be heated too much                                   | Echauffement / surchauffer                     |
| Coolant            | A substance used to reduce the temperature of a system below a certain value                 | Liquide de refroidissement                     |
| Molten             | Heated, melted, fused,... / liquefied by heat                                                | En fusion                                      |
| Intend             | Have in mind, plan,... / to have in mind as something to be done                             | Avoir l'intention                              |
| Grid               | Grate, grill,... / a grating of crossed bars                                                 | Grille                                         |
| Lack               | Require, need, want, be missing,... / absence of something needed or desirable               | Manque / pénurie                               |
| Repository         | Depository, container,... / a container or a place where things are deposited and stored     | Entrepot / dépot                               |
| Waste              | To use up or spend to no profit                                                              | Gaspiller                                      |
| Touted             | ????                                                                                         | Revendu                                        |

## ANALYSIS TABLE ABOUT THE STUDY: 

**Researchers?**

the autor of the article : Mark Fischetti

**Published in? when (if mentioned)?**

Published in Scientific American on July 1, 2019

**General topic**

Nuclear Reactors getting safer

**Procedure/what was examined**

Some industry are hastening development of so-called accident-tolerant fuels that are less able to overheat, and if it work, it will produce very little or no hydrogen. So with this type of fuel, the reactor should not explode anymore.

**Conclusions/discovery**

Improved fuels and growth in small reactors could be a big part of a nuclear power rebirth.

**Remaining questions**



